// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusAPI.Compartilhado;

#nullable disable

namespace NexusAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusAPI.Administracao.Models.Notificacao", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.Property<string>("UsuarioUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USUARIOUID");

                    b.HasKey("UID");

                    b.HasIndex("UsuarioUID");

                    b.ToTable("NOTIFICACOES");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Perfil", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.ToTable("PERFIS");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Projeto", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.ToTable("PROJETOS");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Usuario", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeAcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMEACESSO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SENHA");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.UsuarioProjetoPerfil", b =>
                {
                    b.Property<string>("ProjetoUID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PROJETOUID");

                    b.Property<string>("UsuarioUID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USUARIOUID");

                    b.Property<string>("PerfilUID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PERFILUID");

                    b.Property<bool>("Ativado")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVADO");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("ProjetoUID", "UsuarioUID", "PerfilUID");

                    b.HasIndex("PerfilUID");

                    b.HasIndex("UsuarioUID");

                    b.ToTable("USUARIOPROJETOPERFIL");
                });

            modelBuilder.Entity("NexusAPI.CicloVida.Models.Atribuicao", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<string>("CicloVidaPassoUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CICLOVIDAPASSOUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.Property<string>("UsuarioUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USUARIOUID");

                    b.HasKey("UID");

                    b.HasIndex("CicloVidaPassoUID");

                    b.HasIndex("UsuarioUID");

                    b.ToTable("ATRIBUICOES");
                });

            modelBuilder.Entity("NexusAPI.CicloVida.Models.CicloVida", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("ObjetoUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OBJETOUID");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.ToTable("CICLOSVIDA");
                });

            modelBuilder.Entity("NexusAPI.CicloVida.Models.CicloVidaPasso", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<string>("CicloVidaUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CICLOVIDAUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("PassoFalhaUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSOFALHAUID");

                    b.Property<string>("PassoSucessoUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSOSUCESSOUID");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.HasIndex("CicloVidaUID");

                    b.ToTable("CICLOVIDAPASSOS");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Componente", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAAQUISICAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("LocalizacaoUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LOCALIZACAOUID");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NUMEROSERIE");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.HasIndex("LocalizacaoUID");

                    b.ToTable("COMPONENTES");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Equipamento", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<string>("ComponenteUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COMPONENTEUID");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAAQUISICAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("LocalizacaoUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCALIZACAOUID");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NUMEROSERIE");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.HasIndex("ComponenteUID");

                    b.ToTable("EQUIPAMENTOS");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Localizacao", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.ToTable("LOCALIZACOES");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Manutencao", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<string>("ComponenteUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COMPONENTEUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAINICIO");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATATERMINO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("ResponsavelUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RESPONSAVELUID");

                    b.Property<string>("Solucao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SOLUCAO");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.HasIndex("ComponenteUID");

                    b.HasIndex("ResponsavelUID");

                    b.ToTable("MANUTENCOES");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Requisicao", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<string>("CoordenadorUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COORDENADORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.HasIndex("CoordenadorUID");

                    b.ToTable("REQUISICOES");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Software", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadorPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATUALIZADOPOR");

                    b.Property<string>("ChaveLicenca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHAVELICENCA");

                    b.Property<string>("ComponenteUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COMPONENTEUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAVENCIMENTO");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FINALIZADOPOR");

                    b.Property<string>("LocalizacaoUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LOCALIZACAOUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USUARIOCRIADOR");

                    b.HasKey("UID");

                    b.HasIndex("ComponenteUID");

                    b.HasIndex("LocalizacaoUID");

                    b.ToTable("SOFTWARES");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Notificacao", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.UsuarioProjetoPerfil", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NexusAPI.CicloVida.Models.Atribuicao", b =>
                {
                    b.HasOne("NexusAPI.CicloVida.Models.CicloVidaPasso", "CicloVidaPasso")
                        .WithMany()
                        .HasForeignKey("CicloVidaPassoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CicloVidaPasso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NexusAPI.CicloVida.Models.CicloVidaPasso", b =>
                {
                    b.HasOne("NexusAPI.CicloVida.Models.CicloVida", "CicloVida")
                        .WithMany()
                        .HasForeignKey("CicloVidaUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CicloVida");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Componente", b =>
                {
                    b.HasOne("NexusAPI.Dados.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Equipamento", b =>
                {
                    b.HasOne("NexusAPI.Dados.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Manutencao", b =>
                {
                    b.HasOne("NexusAPI.Dados.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Requisicao", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Coordenador")
                        .WithMany()
                        .HasForeignKey("CoordenadorUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordenador");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Software", b =>
                {
                    b.HasOne("NexusAPI.Dados.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Dados.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");

                    b.Navigation("Localizacao");
                });
#pragma warning restore 612, 618
        }
    }
}
