// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusAPI.Compartilhado.Data;

#nullable disable

namespace NexusAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusAPI.Administracao.Models.Notificacao", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.Property<string>("UsuarioUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOUID");

                    b.Property<bool>("Vista")
                        .HasColumnType("bit")
                        .HasColumnName("VISTA");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.HasIndex("UsuarioUID");

                    b.ToTable("NOTIFICACOES");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Perfil", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("PERFIS");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Projeto", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("PROJETOS", t =>
                        {
                            t.HasTrigger("ProjetosDeletado");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Usuario", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeAcesso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMEACESSO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SENHA");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("USUARIOS", t =>
                        {
                            t.HasTrigger("UsuariosDeletado");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.UsuarioPerfil", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<bool>("Ativado")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVADO");

                    b.Property<string>("AtualizadoPorUID")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("PerfilUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PERFILUID");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.Property<string>("UsuarioUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("PerfilUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.HasIndex("UsuarioUID");

                    b.ToTable("USUARIOPERFIL");
                });

            modelBuilder.Entity("NexusAPI.CicloVidaAtivo.Models.Atribuicao", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit")
                        .HasColumnName("CONCLUIDA");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAVENCIMENTO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("ObjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("OBJETOUID");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.Property<string>("UsuarioUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.HasIndex("UsuarioUID");

                    b.ToTable("ATRIBUICOES");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Componente", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAAQUISICAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("LocalizacaoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LOCALIZACAOUID");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NUMEROSERIE");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("LocalizacaoUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("COMPONENTES", t =>
                        {
                            t.HasTrigger("ComponentesDeletado");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Equipamento", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<string>("ComponenteUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("COMPONENTEUID");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAAQUISICAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("LocalizacaoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LOCALIZACAOUID");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NUMEROSERIE");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("ComponenteUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("LocalizacaoUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("EQUIPAMENTOS");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Localizacao", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("LOCALIZACOES", t =>
                        {
                            t.HasTrigger("LocalizacoesDeletada");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Manutencao", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<string>("ComponenteUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("COMPONENTEUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAINICIO");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATATERMINO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<string>("ResponsavelUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RESPONSAVELUID");

                    b.Property<string>("Solucao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SOLUCAO");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("ComponenteUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("ResponsavelUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("MANUTENCOES", t =>
                        {
                            t.HasTrigger("ManutencoesDeletado");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Requisicao", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<string>("CoordenadorUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("COORDENADORUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("CoordenadorUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("REQUISICOES", t =>
                        {
                            t.HasTrigger("RequisicoesDeletado");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Software", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UID");

                    b.Property<string>("AtualizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ATUALIZADOPORUID");

                    b.Property<string>("ChaveLicenca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CHAVELICENCA");

                    b.Property<string>("ComponenteUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("COMPONENTEUID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACRIACAO");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAFINALIZACAO");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAULTIMAATUALIZACAO");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAVENCIMENTO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FinalizadoPorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FINALIZADOPORUID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("ProjetoUID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PROJETOUID");

                    b.Property<string>("UsuarioCriadorUID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USUARIOCRIADORUID");

                    b.HasKey("UID");

                    b.HasIndex("AtualizadoPorUID");

                    b.HasIndex("ComponenteUID");

                    b.HasIndex("FinalizadoPorUID");

                    b.HasIndex("ProjetoUID");

                    b.HasIndex("UsuarioCriadorUID");

                    b.ToTable("SOFTWARES");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Notificacao", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Perfil", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Projeto", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.Usuario", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Administracao.Models.UsuarioPerfil", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Perfil");

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.CicloVidaAtivo.Models.Atribuicao", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Componente", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Dados.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Localizacao");

                    b.Navigation("Projeto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Equipamento", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Dados.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Dados.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("Componente");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Localizacao");

                    b.Navigation("Projeto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Localizacao", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Projeto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Manutencao", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Dados.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("Componente");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Projeto");

                    b.Navigation("Responsavel");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Requisicao", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "Coordenador")
                        .WithMany()
                        .HasForeignKey("CoordenadorUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("Coordenador");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Projeto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("NexusAPI.Dados.Models.Software", b =>
                {
                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "AtualizadoPor")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUID");

                    b.HasOne("NexusAPI.Dados.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorUID");

                    b.HasOne("NexusAPI.Administracao.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Administracao.Models.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorUID");

                    b.Navigation("AtualizadoPor");

                    b.Navigation("Componente");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Projeto");

                    b.Navigation("UsuarioCriador");
                });
#pragma warning restore 612, 618
        }
    }
}
